### PR TITLE
Revised conversion for Wind from Knots to MPH and KM/H

### PR DESCRIPTION
**Pull request by CompKingCanada**
Revised conversion for Wind from Knots to MPH and KM/H

### CODE REVIEW

**Review by bpaauwe — CHANGES_REQUESTED** [review]
Can you update the titles of the commits?  Just using what you've put in the body would be fine.  When doing a git log --oneline, seeing a bunch of commits titled "update wdpoly.py" doesn't provide any useful information.

I can do this after the fact, but that would make it more difficult for you to pull the updated repository and may lead to conflicts when you do.

**Review by CompKingCanada — COMMENTED** [review]
Looks like you did it already?  I'm still new to GitHub.  I think I did better updating the title on other submissions.

**Comment by CompKingCanada** [comment]
Does the version number need to be incremented to allow updates to be pushed through from GitHub to PolyGlot?

**Comment by bpaauwe** [comment]
> Looks like you did it already? I'm still new to GitHub. I think I did better updating the title on other submissions.

I think I just changed the title of the pull request, not the commit itself.  I was playing around trying to figure out if I could do it as part of the merge, but looks like github doesn't allow that.

> Does the version number need to be incremented to allow updates to be pushed through from GitHub to PolyGlot?

Polyglot pulls from github, and yes, for the node server store to show that there is an update, the version number has to change.  Also, when changing the profile files, the profile version should change too. I think that allows polyglot to push the updated profile files to the ISY.

Typically, after making changes that I want to show up as an update, I'll make a commit that updates the version number in the server.json file, adds an entry to the README.md file describing what changed in this version and commit those with a commit title "Version <new version number>"

**Comment by CompKingCanada** [comment]
The only way I could rename the commit was to create a new one..  I hope this is what you need to merge everything..

**Pull request closed without merging**
